/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package midtermproject;

import java.awt.Color;
import java.io.FileWriter;
import java.io.IOException;
import java.sql.Timestamp;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import java.util.*;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author DELL
 */
public class ManagerFrame extends javax.swing.JFrame {

    /**
     * Creates new form ManagerFrame
     */
    NonConsumableAccessories ncObj = new NonConsumableAccessories();
    ConsumableAccessories cObj = new ConsumableAccessories();
    String searchModel;

    public ManagerFrame() {
        initComponents();
        searchField.setVisible(false);
        searchButton.setVisible(false);
        homeCompanyRadio.setVisible(false);
        homeModelRadio.setVisible(false);
        homePanel.setVisible(false);
        createReqTable1();
        createRecTable();
//        createRecTable(email);
        requestPanel.setVisible(false);
        requestPanel1.setVisible(false);
        managerTable.setOpaque(false);
        generateButton.setVisible(false);
        viewButton1.setVisible(false);
        //Manager.getInstance().fetchRequests(strList);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        adminButton1 = new javax.swing.JButton();
        adminButton2 = new javax.swing.JButton();
        adminButton3 = new javax.swing.JButton();
        adminButton4 = new javax.swing.JButton();
        adminButton5 = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        searchField = new javax.swing.JTextField();
        viewButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        managerTable = new javax.swing.JTable();
        deleteButton = new javax.swing.JButton();
        actionButton = new javax.swing.JButton();
        nonConsumableHome = new javax.swing.JRadioButton();
        consumableHome = new javax.swing.JRadioButton();
        homeComboBox = new javax.swing.JComboBox<>();
        searchButton = new javax.swing.JButton();
        homePanel = new javax.swing.JPanel();
        editButton = new javax.swing.JButton();
        categoryName = new javax.swing.JTextField();
        homeYear = new javax.swing.JTextField();
        homeCompanyName = new javax.swing.JTextField();
        homeModel = new javax.swing.JTextField();
        categoryLabel = new javax.swing.JLabel();
        homeModelLabel = new javax.swing.JLabel();
        homeNameLabel = new javax.swing.JLabel();
        homeYearLabel = new javax.swing.JLabel();
        itemName = new javax.swing.JTextField();
        categoryLabel1 = new javax.swing.JLabel();
        homeModelRadio = new javax.swing.JRadioButton();
        homeCompanyRadio = new javax.swing.JRadioButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        requestTable = new javax.swing.JTable();
        viewButton1 = new javax.swing.JButton();
        requestPanel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        empName = new javax.swing.JTextField();
        empPhone = new javax.swing.JTextField();
        empEmail = new javax.swing.JTextField();
        acceptButton = new javax.swing.JButton();
        rejectButton = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        employeeRequest = new javax.swing.JTable();
        reqIDField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        allRequestTable = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        requestPanel1 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        empName1 = new javax.swing.JTextField();
        empPhone1 = new javax.swing.JTextField();
        empEmail1 = new javax.swing.JTextField();
        jScrollPane5 = new javax.swing.JScrollPane();
        employeeRequest1 = new javax.swing.JTable();
        reqIDField1 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jButton10 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        itemComboBox = new javax.swing.JComboBox<>();
        consumableRadio = new javax.swing.JRadioButton();
        nonConsumableRadio = new javax.swing.JRadioButton();
        modelLabel = new javax.swing.JLabel();
        nameLabel = new javax.swing.JLabel();
        yearLabel = new javax.swing.JLabel();
        modelField = new javax.swing.JTextField();
        companyName = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        generateButton = new javax.swing.JButton();
        jCalendar1 = new com.toedter.calendar.JCalendar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 0, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Dashboard");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 46, 194, 96));

        adminButton1.setBackground(new java.awt.Color(255, 0, 51));
        adminButton1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        adminButton1.setForeground(new java.awt.Color(255, 255, 255));
        adminButton1.setText("Home Page");
        adminButton1.setBorder(null);
        adminButton1.setFocusable(false);
        adminButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                adminButton1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                adminButton1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                adminButton1MouseExited(evt);
            }
        });
        adminButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(adminButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, 341, 90));

        adminButton2.setBackground(new java.awt.Color(255, 0, 51));
        adminButton2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        adminButton2.setForeground(new java.awt.Color(255, 255, 255));
        adminButton2.setText("Add Accessories");
        adminButton2.setBorder(null);
        adminButton2.setFocusable(false);
        adminButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                adminButton2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                adminButton2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                adminButton2MouseExited(evt);
            }
        });
        adminButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(adminButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 550, 341, 90));

        adminButton3.setBackground(new java.awt.Color(255, 0, 51));
        adminButton3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        adminButton3.setForeground(new java.awt.Color(255, 255, 255));
        adminButton3.setText("Logout");
        adminButton3.setBorder(null);
        adminButton3.setFocusable(false);
        adminButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                adminButton3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                adminButton3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                adminButton3MouseExited(evt);
            }
        });
        adminButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(adminButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 660, 341, 90));

        adminButton4.setBackground(new java.awt.Color(255, 0, 51));
        adminButton4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        adminButton4.setForeground(new java.awt.Color(255, 255, 255));
        adminButton4.setText("Requests");
        adminButton4.setBorder(null);
        adminButton4.setFocusable(false);
        adminButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                adminButton4MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                adminButton4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                adminButton4MouseExited(evt);
            }
        });
        adminButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(adminButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 330, 341, 90));

        adminButton5.setBackground(new java.awt.Color(255, 0, 51));
        adminButton5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        adminButton5.setForeground(new java.awt.Color(255, 255, 255));
        adminButton5.setText("Receipts");
        adminButton5.setBorder(null);
        adminButton5.setFocusable(false);
        adminButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                adminButton5MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                adminButton5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                adminButton5MouseExited(evt);
            }
        });
        adminButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(adminButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 440, 341, 90));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 0, 340, 810));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setEnabled(false);
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        searchField.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        searchField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchFieldActionPerformed(evt);
            }
        });
        jPanel2.add(searchField, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 240, 340, 57));

        viewButton.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        viewButton.setText("View");
        viewButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewButtonActionPerformed(evt);
            }
        });
        jPanel2.add(viewButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 630, 136, 57));

        managerTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        managerTable.setGridColor(new java.awt.Color(255, 255, 255));
        managerTable.setOpaque(false);
        managerTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                managerTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(managerTable);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 380, 490, 213));

        deleteButton.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        deleteButton.setText("Delete");
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });
        jPanel2.add(deleteButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 630, 136, 57));

        actionButton.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        actionButton.setText("By Search");
        actionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actionButtonActionPerformed(evt);
            }
        });
        jPanel2.add(actionButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 160, 160, 57));

        nonConsumableHome.setBackground(new java.awt.Color(255, 255, 255));
        nonConsumableHome.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        nonConsumableHome.setText("Non Consumable Item");
        nonConsumableHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nonConsumableHomeActionPerformed(evt);
            }
        });
        jPanel2.add(nonConsumableHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 90, -1, -1));

        consumableHome.setBackground(new java.awt.Color(255, 255, 255));
        consumableHome.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        consumableHome.setText("Consumable Item");
        consumableHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consumableHomeActionPerformed(evt);
            }
        });
        jPanel2.add(consumableHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 90, -1, -1));

        homeComboBox.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        homeComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeComboBoxActionPerformed(evt);
            }
        });
        jPanel2.add(homeComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 170, 260, -1));

        searchButton.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        searchButton.setText("Search");
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });
        jPanel2.add(searchButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 240, 136, 57));

        homePanel.setBackground(new java.awt.Color(255, 255, 255));

        editButton.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        editButton.setText("Edit");
        editButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editButtonActionPerformed(evt);
            }
        });

        categoryName.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        homeYear.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        homeCompanyName.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        homeModel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        categoryLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        categoryLabel.setText("Item");

        homeModelLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        homeModelLabel.setText("Model");

        homeNameLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        homeNameLabel.setText("Company Name");

        homeYearLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        homeYearLabel.setText("Date Of Manufacture");

        itemName.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        categoryLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        categoryLabel1.setText("Category");

        javax.swing.GroupLayout homePanelLayout = new javax.swing.GroupLayout(homePanel);
        homePanel.setLayout(homePanelLayout);
        homePanelLayout.setHorizontalGroup(
            homePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(homePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(homePanelLayout.createSequentialGroup()
                        .addComponent(homeModelLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(homeModel, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(homePanelLayout.createSequentialGroup()
                        .addComponent(homeNameLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(homeCompanyName, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(homePanelLayout.createSequentialGroup()
                        .addComponent(homeYearLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                        .addGroup(homePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(editButton, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(homeYear, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(homePanelLayout.createSequentialGroup()
                        .addComponent(categoryLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(categoryName, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(homePanelLayout.createSequentialGroup()
                        .addComponent(categoryLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(itemName, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        homePanelLayout.setVerticalGroup(
            homePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, homePanelLayout.createSequentialGroup()
                .addContainerGap(52, Short.MAX_VALUE)
                .addGroup(homePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(itemName, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(categoryLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(homePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(categoryName, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(categoryLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(homePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(homeCompanyName, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(homeNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(homePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(homeModel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(homeModelLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(homePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(homeYear, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(homeYearLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(53, 53, 53)
                .addComponent(editButton, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );

        jPanel2.add(homePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, 490, 440));

        homeModelRadio.setBackground(new java.awt.Color(255, 255, 255));
        homeModelRadio.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        homeModelRadio.setText("Model");
        homeModelRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeModelRadioActionPerformed(evt);
            }
        });
        jPanel2.add(homeModelRadio, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 320, -1, -1));

        homeCompanyRadio.setBackground(new java.awt.Color(255, 255, 255));
        homeCompanyRadio.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        homeCompanyRadio.setText("Company Name");
        homeCompanyRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeCompanyRadioActionPerformed(evt);
            }
        });
        jPanel2.add(homeCompanyRadio, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 320, -1, -1));

        jTabbedPane1.addTab("tab1", jPanel2);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        requestTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        requestTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                requestTableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(requestTable);

        jPanel3.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 130, 570, 380));

        viewButton1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        viewButton1.setText("View");
        viewButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(viewButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 530, 136, 57));

        requestPanel.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Request ID: ");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Phone No.: ");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Email: ");

        empName.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        empPhone.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        empEmail.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        acceptButton.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        acceptButton.setText("Accept");
        acceptButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acceptButtonActionPerformed(evt);
            }
        });

        rejectButton.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        rejectButton.setText("Reject");
        rejectButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rejectButtonActionPerformed(evt);
            }
        });

        employeeRequest.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane3.setViewportView(employeeRequest);

        reqIDField.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Employee Name: ");

        javax.swing.GroupLayout requestPanelLayout = new javax.swing.GroupLayout(requestPanel);
        requestPanel.setLayout(requestPanelLayout);
        requestPanelLayout.setHorizontalGroup(
            requestPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(requestPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(68, 68, 68)
                .addComponent(reqIDField, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(requestPanelLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(acceptButton, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57)
                .addComponent(rejectButton, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(requestPanelLayout.createSequentialGroup()
                .addGroup(requestPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(requestPanelLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel6))
                    .addGroup(requestPanelLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel4))
                    .addGroup(requestPanelLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel5)))
                .addGap(31, 31, 31)
                .addGroup(requestPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(empEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(empPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(empName, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        requestPanelLayout.setVerticalGroup(
            requestPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(requestPanelLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(requestPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(reqIDField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(requestPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(requestPanelLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel6))
                    .addComponent(empName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(requestPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(empPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(requestPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(empEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63)
                .addGroup(requestPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(acceptButton, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rejectButton, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jPanel3.add(requestPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 780));

        jTabbedPane1.addTab("tab2", jPanel3);

        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        allRequestTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        allRequestTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                allRequestTableMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(allRequestTable);

        jPanel6.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 200, 544, 302));
        jPanel6.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(402, 77, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel8.setText("Receipts");
        jPanel6.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(644, 115, -1, -1));

        jButton6.setBackground(new java.awt.Color(51, 102, 255));
        jButton6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setText("View");
        jButton6.setFocusable(false);
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 540, 104, 50));

        jButton7.setBackground(new java.awt.Color(51, 102, 255));
        jButton7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton7.setForeground(new java.awt.Color(255, 255, 255));
        jButton7.setText("Remove");
        jButton7.setFocusable(false);
        jPanel6.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 540, -1, 50));

        jButton8.setBackground(new java.awt.Color(51, 102, 255));
        jButton8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton8.setForeground(new java.awt.Color(255, 255, 255));
        jButton8.setText("Remove All");
        jButton8.setFocusable(false);
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 540, -1, 50));

        requestPanel1.setBackground(new java.awt.Color(255, 255, 255));
        requestPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setText("Request ID: ");
        requestPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 23, -1, 30));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel10.setText("Phone No.: ");
        requestPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 141, -1, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel11.setText("Email: ");
        requestPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 195, -1, -1));

        empName1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        requestPanel1.add(empName1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 80, 175, -1));

        empPhone1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        requestPanel1.add(empPhone1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 138, 175, -1));

        empEmail1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        requestPanel1.add(empEmail1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 192, 175, -1));

        employeeRequest1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane5.setViewportView(employeeRequest1);

        requestPanel1.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 400, 328));

        reqIDField1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        requestPanel1.add(reqIDField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 24, 175, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel12.setText("Employee Name: ");
        requestPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 83, -1, -1));

        jButton10.setBackground(new java.awt.Color(51, 102, 255));
        jButton10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton10.setForeground(new java.awt.Color(255, 255, 255));
        jButton10.setText("Close");
        jButton10.setFocusable(false);
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        requestPanel1.add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 690, 104, 50));

        jPanel6.add(requestPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 430, 780));

        jPanel4.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1305, 780));

        jTabbedPane1.addTab("tab3", jPanel4);

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Select Item");
        jPanel5.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(156, 209, -1, 28));

        itemComboBox.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jPanel5.add(itemComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(392, 209, 200, -1));

        consumableRadio.setBackground(new java.awt.Color(255, 255, 255));
        consumableRadio.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        consumableRadio.setText("Consumable Item");
        consumableRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consumableRadioActionPerformed(evt);
            }
        });
        jPanel5.add(consumableRadio, new org.netbeans.lib.awtextra.AbsoluteConstraints(156, 114, -1, -1));

        nonConsumableRadio.setBackground(new java.awt.Color(255, 255, 255));
        nonConsumableRadio.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        nonConsumableRadio.setText("Non Consumable Item");
        nonConsumableRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nonConsumableRadioActionPerformed(evt);
            }
        });
        jPanel5.add(nonConsumableRadio, new org.netbeans.lib.awtextra.AbsoluteConstraints(392, 114, -1, -1));

        modelLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        modelLabel.setText("Model");
        jPanel5.add(modelLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(156, 414, -1, 28));

        nameLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        nameLabel.setText("Company Name");
        jPanel5.add(nameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(156, 330, -1, 28));

        yearLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        yearLabel.setText("Year of Manufacture");
        jPanel5.add(yearLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(156, 499, -1, 36));

        modelField.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        modelField.setText("XXX-0000");
        modelField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                modelFieldMouseClicked(evt);
            }
        });
        jPanel5.add(modelField, new org.netbeans.lib.awtextra.AbsoluteConstraints(392, 408, 270, 40));

        companyName.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        companyName.setText("NAME");
        companyName.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                companyNameMouseClicked(evt);
            }
        });
        jPanel5.add(companyName, new org.netbeans.lib.awtextra.AbsoluteConstraints(392, 324, 270, 40));

        jButton5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton5.setText("Done");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 700, 112, 53));

        generateButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        generateButton.setText("Generate Tag");
        generateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generateButtonActionPerformed(evt);
            }
        });
        jPanel5.add(generateButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 400, 150, 53));
        jPanel5.add(jCalendar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 490, 310, 190));

        jTabbedPane1.addTab("tab4", jPanel5);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 0, 1280, 810));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void adminButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_adminButton1MouseClicked
        //jTabbedPane1.setSelectedIndex(0);
        // TODO add your handling code here:
    }//GEN-LAST:event_adminButton1MouseClicked

    private void adminButton1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_adminButton1MouseEntered

        adminButton1.setBackground(Color.white);
        adminButton1.setForeground(new Color(0, 0, 0));
        // TODO add your handling code here:
    }//GEN-LAST:event_adminButton1MouseEntered

    private void adminButton1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_adminButton1MouseExited
        adminButton1.setBackground(new Color(255, 0, 51));
        adminButton1.setForeground(new Color(255, 255, 255));
        // TODO add your handling code here:
    }//GEN-LAST:event_adminButton1MouseExited

    private void adminButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminButton1ActionPerformed
        jTabbedPane1.setSelectedIndex(0);
        // TODO add your handling code here:
    }//GEN-LAST:event_adminButton1ActionPerformed

    private void adminButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_adminButton2MouseClicked

        // TODO add your handling code here:sksyuaifgiabigibaiiaijbywguygwu
    }//GEN-LAST:event_adminButton2MouseClicked

    private void adminButton2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_adminButton2MouseEntered
        adminButton2.setBackground(Color.white);
        adminButton2.setForeground(new Color(0, 0, 0));
        // TODO add your handling code here:
    }//GEN-LAST:event_adminButton2MouseEntered

    private void adminButton2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_adminButton2MouseExited
        adminButton2.setBackground(new Color(255, 0, 51));
        adminButton2.setForeground(new Color(255, 255, 255));
        // TODO add your handling code here:
    }//GEN-LAST:event_adminButton2MouseExited

    private void adminButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminButton2ActionPerformed
        jTabbedPane1.setSelectedIndex(3);
        // TODO add your handling code here:
    }//GEN-LAST:event_adminButton2ActionPerformed

    private void adminButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_adminButton3MouseClicked

        // TODO add your handling code here:
    }//GEN-LAST:event_adminButton3MouseClicked

    private void adminButton3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_adminButton3MouseEntered

        adminButton3.setBackground(Color.white);
        adminButton3.setForeground(new Color(0, 0, 0));
        // TODO add your handling code here:
    }//GEN-LAST:event_adminButton3MouseEntered

    private void adminButton3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_adminButton3MouseExited
        adminButton3.setBackground(new Color(255, 0, 51));
        adminButton3.setForeground(new Color(255, 255, 255));
        // TODO add your handling code here:
    }//GEN-LAST:event_adminButton3MouseExited

    private void adminButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminButton3ActionPerformed
        Login form = new Login();
        this.setVisible(false);
        form.setVisible(true);
        Manager.getInstance().saveAccessories();
    }//GEN-LAST:event_adminButton3ActionPerformed

    private void adminButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_adminButton4MouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_adminButton4MouseClicked

    private void adminButton4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_adminButton4MouseEntered
        // TODO add your handling code here:
        adminButton4.setBackground(Color.white);
        adminButton4.setForeground(new Color(0, 0, 0));
    }//GEN-LAST:event_adminButton4MouseEntered

    private void adminButton4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_adminButton4MouseExited
        // TODO add your handling code here:
        adminButton4.setBackground(new Color(255, 0, 51));
        adminButton4.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_adminButton4MouseExited

    private void adminButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminButton4ActionPerformed
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(1);
    }//GEN-LAST:event_adminButton4ActionPerformed

    private void adminButton5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_adminButton5MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_adminButton5MouseClicked

    private void adminButton5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_adminButton5MouseEntered
        // TODO add your handling code here:
        adminButton5.setBackground(Color.white);
        adminButton5.setForeground(new Color(0, 0, 0));
    }//GEN-LAST:event_adminButton5MouseEntered

    private void adminButton5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_adminButton5MouseExited
        // TODO add your handling code here:
        adminButton5.setBackground(new Color(255, 0, 51));
        adminButton5.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_adminButton5MouseExited

    private void adminButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminButton5ActionPerformed
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(2);
    }//GEN-LAST:event_adminButton5ActionPerformed

    private void searchFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchFieldActionPerformed

    private void viewButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewButtonActionPerformed
        homePanel.setVisible(true);
        if (nonConsumableHome.isSelected()) {
            showDataN();
        } else if (consumableHome.isSelected()) {
            showDataC();
            homeYearLabel.setText("Received Date");
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_viewButtonActionPerformed

    private void editButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editButtonActionPerformed
        // TODO add your handling code here:
        if (editButton.getText().equals("Edit")) {
            //itemName.setEditable(true);
            categoryName.setEditable(true);
            homeCompanyName.setEditable(true);
            homeModel.setEditable(true);
            homeYear.setEditable(true);
            editButton.setText("Save");
        } else if (editButton.getText().equals("Save")) {
            String item = itemName.getText();
            String name = categoryName.getText();
            String company = homeCompanyName.getText();
            String model = homeModel.getText();
            String year = homeYear.getText();
            if (item.equals("Non Consumable")) {
                NonConsumableAccessories obj = new NonConsumableAccessories();
                obj.setCompanyName(company);
                obj.setModel(model);
                obj.setYearOfManufacture(year);
                obj.setType(name);

                boolean check = Manager.getInstance().editNonConsumableAccessories(obj, searchModel);
                JOptionPane.showMessageDialog(null, check);
            } else if (item.equals("Consumable")) {
                ConsumableAccessories obj = new ConsumableAccessories();
                obj.setCompanyName(company);
                obj.setTag(model);
                //obj.setYearOfManufacture(year);
                obj.setType(name);
                Manager.getInstance().editConsumableAccessories(obj, searchModel);
            }
            editButton.setText("Edit");
            homePanel.setVisible(false);
            itemName.setText("");
            categoryName.setText("");
            homeCompanyName.setText("");
            homeModel.setText("");
            homeYear.setText("");
        }
    }//GEN-LAST:event_editButtonActionPerformed

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        // TODO add your handling code here:
        if (consumableHome.isSelected()) {
            boolean flag = Manager.getInstance().deleteConsumableAccessories(searchModel);
            if (flag) {
                JOptionPane.showMessageDialog(null, "Deleted Successfully");
            } else {
                JOptionPane.showMessageDialog(null, "Unable to complete the operation");
            }
        } else if (nonConsumableHome.isSelected()) {
            boolean flag = Manager.getInstance().deleteNonConsumableAccessories(searchModel);
            if (flag) {
                JOptionPane.showMessageDialog(null, "Deleted Successfully");
            } else {
                JOptionPane.showMessageDialog(null, "Unable to complete the operation");
            }
        }
    }//GEN-LAST:event_deleteButtonActionPerformed

    private void actionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actionButtonActionPerformed
        // TODO add your handling code here:
        if (actionButton.getText().equals("By Search")) {
            searchField.setVisible(true);
            searchButton.setVisible(true);
            actionButton.setText("By List");
            homeComboBox.setVisible(false);
            homeCompanyRadio.setVisible(true);
            if (!homeModelRadio.isShowing() && nonConsumableHome.isSelected()) {
                homeModelRadio.setVisible(true);
            }
        } else if (actionButton.getText().equals("By List")) {
            searchField.setVisible(false);
            searchButton.setVisible(false);
            actionButton.setText("By Search");
            homeComboBox.setVisible(true);
            homeCompanyRadio.setVisible(false);

            homeModelRadio.setVisible(false);

        }

    }//GEN-LAST:event_actionButtonActionPerformed

    private void nonConsumableRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nonConsumableRadioActionPerformed
        // TODO add your handling code here:
        jCalendar1.setVisible(true);
        generateButton.setVisible(false);
        modelLabel.setText("Model");
        modelField.setText("");
        modelField.setEditable(true);
        consumableRadio.setSelected(false);
        modelLabel.setVisible(true);
        yearLabel.setVisible(true);
        modelField.setVisible(true);
        // yearField.setVisible(true);
        DefaultComboBoxModel model = new DefaultComboBoxModel();
        //  itemComboBox = new JComboBox();
        model.addElement("Laptop");
        model.addElement("Projector");
        model.addElement("Chair");
        model.addElement("Mobile");
        model.addElement("Computer");
        itemComboBox.setModel(model);
        //String[] array = {"Laptop","Projector","Chair","Mobile","Computer"};
        //itemComboBox = new JComboBox(array);
    }//GEN-LAST:event_nonConsumableRadioActionPerformed

    private void consumableRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consumableRadioActionPerformed
        // TODO add your handling code here:
        jCalendar1.setVisible(false);
        generateButton.setVisible(true);
        nonConsumableRadio.setSelected(false);
        //modelLabel.setVisible(false);
        modelLabel.setText("Tag No. ");
        yearLabel.setVisible(false);
        modelField.setEditable(false);
        // modelField.setVisible(false);
        // yearField.setVisible(false);
        DefaultComboBoxModel model = new DefaultComboBoxModel();
        //  itemComboBox = new JComboBox();
        model.addElement("File");
        model.addElement("Paper");
        model.addElement("Pencil");
        model.addElement("Note Book");
        model.addElement("Paper Clips");
        itemComboBox.setModel(model);
        // String[] array = {"File","Paper","Pencil","NoteBook","Paper Clips"};

    }//GEN-LAST:event_consumableRadioActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        if (nonConsumableRadio.isSelected()) {
            String Type = (String) itemComboBox.getSelectedItem();
            String cName = companyName.getText();
            String model = modelField.getText();
            Date dt = jCalendar1.getDate();
            boolean a = Manager.getInstance().validName(cName);
            boolean b = Manager.getInstance().validateModel(model);
            Timestamp ts = new Timestamp(dt.getTime());
            String year = "" + ts;
            if (a == true && b == true) {
                NonConsumableAccessories obj = new NonConsumableAccessories();
                obj.setModel(model);
                obj.setType(Type);
                obj.setCompanyName(cName);
                obj.setYearOfManufacture(year);
                boolean check = Manager.getInstance().addNonConsumableAccessories(obj);
                if (check) {
                    JOptionPane.showMessageDialog(null, "Saved successfully");
                } else {
                    JOptionPane.showMessageDialog(null, "unable to save data");
                }
            } else {
                JOptionPane.showMessageDialog(null, "Invalid Input");
            }
        } else if (consumableRadio.isSelected()) {
            String Type = (String) itemComboBox.getSelectedItem();
            String cName = companyName.getText();
            String tag = modelField.getText();
            boolean a = Manager.getInstance().validName(cName);
            Date date = new Date();
            Timestamp ts = new Timestamp(date.getTime());
            if (a) {
                ConsumableAccessories obj = new ConsumableAccessories();
                obj.setCompanyName(cName);
                obj.setType(Type);
                obj.setTag(tag);
                obj.setTime(ts);
                boolean check = Manager.getInstance().addConsumableAccessories(obj);
                if (check) {
                    JOptionPane.showMessageDialog(null, "Saved successfully");
                } else {
                    JOptionPane.showMessageDialog(null, "unable to save data");
                }
            } else {
                JOptionPane.showMessageDialog(null, "invalid input");
            }
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void nonConsumableHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nonConsumableHomeActionPerformed
        // TODO add your handling code here:
        if (actionButton.getText().equals("By List")) {
            homeModelRadio.setVisible(true);
        } else {
            homeModelRadio.setVisible(false);
        }
        consumableHome.setSelected(false);
        DefaultComboBoxModel model = new DefaultComboBoxModel();
        model.addElement("None");
        model.addElement("Laptop");
        model.addElement("Projector");
        model.addElement("Chair");
        model.addElement("Mobile");
        model.addElement("Computer");
        homeComboBox.setModel(model);
    }//GEN-LAST:event_nonConsumableHomeActionPerformed

    private void consumableHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consumableHomeActionPerformed
        // TODO add your handling code here:
        homeModelRadio.setVisible(false);
        nonConsumableHome.setSelected(false);
        DefaultComboBoxModel model = new DefaultComboBoxModel();
        model.addElement("None");
        model.addElement("File");
        model.addElement("Paper");
        model.addElement("Pencil");
        model.addElement("Note Book");
        model.addElement("Paper Clips");
        homeComboBox.setModel(model);
    }//GEN-LAST:event_consumableHomeActionPerformed

    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchButtonActionPerformed

    private void homeModelRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeModelRadioActionPerformed
        // TODO add your handling code here:
        homeCompanyRadio.setSelected(false);
    }//GEN-LAST:event_homeModelRadioActionPerformed

    private void homeCompanyRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeCompanyRadioActionPerformed
        // TODO add your handling code here:
        homeModelRadio.setSelected(false);
    }//GEN-LAST:event_homeCompanyRadioActionPerformed

    private void homeComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeComboBoxActionPerformed
        // TODO add your handling code here:
        if (!homeComboBox.getSelectedItem().equals("None")) {
            String category = (String) homeComboBox.getSelectedItem();
            //JOptionPane.showMessageDialog(null,category);
            if (consumableHome.isSelected()) {
                List<ConsumableAccessories> strList = Manager.getInstance().viewByCategoryC(category);
                createManagerTableC(strList);
            } else if (nonConsumableHome.isSelected()) {
                List<NonConsumableAccessories> strList = Manager.getInstance().viewByCategoryN(category);
                createManagerTableN(strList);
            }
        }
    }//GEN-LAST:event_homeComboBoxActionPerformed

    private void managerTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_managerTableMouseClicked
        // TODO add your handling code here:
        ListSelectionModel m = managerTable.getSelectionModel();
        DefaultTableModel model = (DefaultTableModel) managerTable.getModel();
        int rowIndex = m.getMinSelectionIndex();
        String input = (String) model.getValueAt(rowIndex, 1);
        if (nonConsumableHome.isSelected()) {
            ncObj = Manager.getInstance().getDataN(input);
        } else if (consumableHome.isSelected()) {
            cObj = Manager.getInstance().getDataC(input);
        }
        searchModel = input;

    }//GEN-LAST:event_managerTableMouseClicked

    String[][] employeeRequestData() {
        Manager obj = Manager.getInstance();
        int r = obj.reqList.size();
        int c = 4;
        String array[][] = new String[r][c];
        String var = "";
        for (int i = 0; i < obj.reqList.size(); i++) {
            var = var + obj.reqList.get(i).getReqID() + ",";
            var = var + obj.reqList.get(i).email + ",";
            var = var + obj.reqList.get(i).getStatus() + ",";
            var = var + obj.reqList.get(i).getTimeq();
            if (i < obj.reqList.size() - 1) {
                var = var + ",";
            }
        }
        String arr[] = var.split(",");
        int k = 0;
        for (int i = 0; i < r; i++) {
            for (int j = 0; j < c; j++) {
                if (i < arr.length) {
                    array[i][j] = arr[k];
                    k++;
                }
            }
        }
        return array;
    }

    void createReqTable1() {
        String[][] rowData = employeeRequestData();
        String[] columnHeader = {"Req ID", "Employee Email", "Status", "Date & Time"};
        DefaultTableModel model = (DefaultTableModel) requestTable.getModel();
        model.setDataVector(rowData, columnHeader);
    }

    private void viewButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewButton1ActionPerformed
        // TODO add your handling code here:
        requestPanel.setVisible(true);

    }//GEN-LAST:event_viewButton1ActionPerformed

    private void requestTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_requestTableMouseClicked
        // TODO add your handling code here:

        ListSelectionModel m = requestTable.getSelectionModel();
        DefaultTableModel model = (DefaultTableModel) requestTable.getModel();
        int rowIndex = m.getMinSelectionIndex();
        String email = (String) model.getValueAt(rowIndex, 1);
        String reqID = (String) model.getValueAt(rowIndex, 0);
        Request reqObj = Manager.getInstance().searchReqID(reqID);
        Employee empObj = Admin.getInstance().viewEmployee(email);
        showEmployeeRequest(empObj, reqObj);
        viewButton1.setVisible(true);
    }//GEN-LAST:event_requestTableMouseClicked

    private void acceptButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acceptButtonActionPerformed
        // TODO add your handling code here:
         createReqTable1();
        createRecTable();
        viewButton1.setVisible(true);
        String id = reqIDField.getText();
        Request obj = Manager.getInstance().searchReqID(id);
        boolean check = Manager.getInstance().acceptRequest(obj);
        Receipt rec = new Receipt();
        if (check) {
            rec = Manager.getInstance().createEmployeeReceipt(id);
            Employee emp = Admin.getInstance().viewEmployee(rec.getEmail());
            emp.setRec(rec);
            Manager.getInstance().addReceipt(rec);
            createReceipt(id);
            JOptionPane.showMessageDialog(null, "Operation Successful");
        } else {
            JOptionPane.showMessageDialog(null, "Operation was not Successful");
        }
        reqIDField.setText("");
        empName.setText("");
        empPhone.setText("");
        empEmail.setText("");
        requestPanel.setVisible(false);

    }//GEN-LAST:event_acceptButtonActionPerformed

    void createReceipt(String id) {
        Request obj = Manager.getInstance().searchReqID(id);
        String email = Manager.getInstance().returnEmail(obj.getReqID());
        Employee obj12 = Admin.getInstance().viewEmployee(email);
        List<NonConsumableAccessories> nList = obj.getnList();
        List<ConsumableAccessories> cList = obj.getcList();
        try {
            FileWriter fr = new FileWriter("Receipt.txt");
            String out1 = String.format("Employee Name: " + obj12.getName() + "\n" + "Email: " + obj12.getEmail() + "\n" + "Phone Number: " + obj12.getCellNumber() + "\n");
            String input = "";
            String temp = "";
            int r = nList.size() + cList.size();
            int c = 4;
            //  out1 = out1 + String.format("%-30s,%-30s,%-30s,%-30s","Company Name","Model","Item","Type");
            for (int i = 0; i < nList.size(); i++) {
                temp = temp + nList.get(i).getCompanyName() + ",";
                temp = temp + nList.get(i).getModel() + ",";
                temp = temp + nList.get(i).getType() + ",";
                temp = temp + "Non Consumable" + "\n";

            }
            for (int i = 0; i < cList.size(); i++) {
                input = input + cList.get(i).getCompanyName() + ",";
                input = input + cList.get(i).getTag() + ",";
                input = input + cList.get(i).getType() + ",";
                input = input + "Consumable";
                input = input + "\n";

            }
            String out = "";
            if (!temp.equals("") && (!input.equals(""))) {
                out = temp + "," + input;
            } else if (!temp.equals("")) {
                out = temp;
            } else if (!input.equals("")) {
                out = input;
            }

            out1 = out1 + out;
            fr.write(out1);
            fr.flush();
            fr.close();
        } catch (Exception ex) {

        }
    }
    private void rejectButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rejectButtonActionPerformed
        // TODO add your handling code here:
         createReqTable1();
        viewButton1.setVisible(true);
        createRecTable();
        String id = reqIDField.getText();
        Request obj = Manager.getInstance().searchReqID(id);
        boolean check = Manager.getInstance().rejectRequest(obj);
        if (check) {
            JOptionPane.showMessageDialog(null, "Operation Successful");
        } else {
            JOptionPane.showMessageDialog(null, "Operation was not Successful");
        }
        reqIDField.setText("");
        empName.setText("");
        empPhone.setText("");
        empEmail.setText("");
        requestPanel.setVisible(false);
    }//GEN-LAST:event_rejectButtonActionPerformed

    private void allRequestTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_allRequestTableMouseClicked
        // TODO add your handling code here:
        ListSelectionModel m = allRequestTable.getSelectionModel();
        DefaultTableModel model = (DefaultTableModel) allRequestTable.getModel();
        int rowIndex = m.getMinSelectionIndex();

        String reqID = (String) model.getValueAt(rowIndex, 1);
        String email = Manager.getInstance().returnEmail(reqID);
        Employee emp = Admin.getInstance().viewEmployee(email);
        Receipt recObj = Manager.getInstance().searchRecID(reqID);
        showEmployeeRec(recObj, emp);
    }//GEN-LAST:event_allRequestTableMouseClicked

    void showEmployeeRec(Receipt rec, Employee emp) {
        empName1.setText(emp.getName());
        empPhone1.setText(emp.getCellNumber());
        empEmail1.setText(emp.getEmail());
        reqIDField1.setText(rec.getReqID());
        reqIDField1.setEditable(false);
        empName1.setEditable(false);
        empPhone1.setEditable(false);
        empEmail1.setEditable(false);
        String[][] rowData = createEmployeeRecTable(rec.getnList(), rec.getcList());
        String[] columnHeader = {"Company", "Tag", "Item", "Type"};
        DefaultTableModel model = (DefaultTableModel) employeeRequest1.getModel();
        model.setDataVector(rowData, columnHeader);

    }

    String[][] createEmployeeRecTable(List<NonConsumableAccessories> nList, List<ConsumableAccessories> cList) {
        int r = nList.size() + cList.size();
        int c = 4;
        String array[][] = new String[r][c];
        String temp = "";
        String input = "";
        for (int i = 0; i < nList.size(); i++) {
            temp = temp + nList.get(i).getCompanyName() + ",";
            temp = temp + nList.get(i).getModel() + ",";
            temp = temp + nList.get(i).getType() + ",";
            temp = temp + "Non Consumable";
            if (i < nList.size() - 1) {
                temp = temp + ",";
            }
        }
        for (int i = 0; i < cList.size(); i++) {
            input = input + cList.get(i).getCompanyName() + ",";
            input = input + cList.get(i).getTag() + ",";
            input = input + cList.get(i).getType() + ",";
            input = input + "Consumable";
            if (i < cList.size() - 1) {
                input = input + ",";
            }
        }
        String out = "";
        if (!temp.equals("") && (!input.equals(""))) {
            out = temp + "," + input;
        } else if (!temp.equals("")) {
            out = temp;
        } else if (!input.equals("")) {
            out = input;
        }
        String arr[] = out.split(",");
        int k = 0;

        for (int i = 0; i < r; i++) {
            for (int j = 0; j < c; j++) {
                if (k < arr.length) {
                    array[i][j] = arr[k];
                    k++;
                }
            }
        }
        return array;
    }

    String[][] showrecList(List<Receipt> strList) {
        int r = strList.size();
        int c = 3;
        String[][] array = new String[r][c];
        String var = "";
        int sr = 1;
        for (int i = 0; i < strList.size(); i++) {
            var = var + sr + ",";
            var = var + strList.get(i).getReqID() + ",";
            var = var + strList.get(i).getTimeq();
            if (i < strList.size()) {
                var = var + ",";
            }
        }
        String[] arr = var.split(",");
        int k = 0;
        for (int i = 0; i < r; i++) {
            for (int j = 0; j < c; j++) {
                if (k < arr.length) {
                    array[i][j] = arr[k];
                    k++;
                }
            }
        }
        return array;
    }

    void createRecTable() {
        List<Receipt> list = Manager.getInstance().recList;
        String[][] rowData = showrecList(list);
        String[] columnHeader = {"Sr No.", "Receipt ID", "Date & Time"};
        DefaultTableModel model = (DefaultTableModel) allRequestTable.getModel();
        model.setDataVector(rowData, columnHeader);
    }


    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        requestPanel1.setVisible(true);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
        
        empName.setText("");
        empPhone.setText("");
        empEmail.setText("");
        reqIDField.setText("");
        requestPanel1.setVisible(false);
    }//GEN-LAST:event_jButton10ActionPerformed

    private void generateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generateButtonActionPerformed
        // TODO add your handling code here:
        modelField.setText(Manager.getInstance().generateTag());
    }//GEN-LAST:event_generateButtonActionPerformed

    private void modelFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_modelFieldMouseClicked
        // TODO add your handling code here:
        modelField.setText("");
    }//GEN-LAST:event_modelFieldMouseClicked

    private void companyNameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_companyNameMouseClicked
        // TODO add your handling code here:
        companyName.setText("");
    }//GEN-LAST:event_companyNameMouseClicked

    void showEmployeeRequest(Employee emp, Request req) {
        empName.setText(emp.getName());
        empPhone.setText(emp.getCellNumber());
        empEmail.setText(emp.getEmail());
        reqIDField.setText(req.getReqID());
        reqIDField.setEditable(false);
        empName.setEditable(false);
        empPhone.setEditable(false);
        empEmail.setEditable(false);
        String[][] rowData = createEmployeeReqTable(req.getnList(), req.getcList());
        String[] columnHeader = {"Company", "Tag", "Item", "Type"};
        DefaultTableModel model = (DefaultTableModel) employeeRequest.getModel();
        model.setDataVector(rowData, columnHeader);
    }

    String[][] createEmployeeReqTable(List<NonConsumableAccessories> nList, List<ConsumableAccessories> cList) {
        int r = nList.size() + cList.size();
        int c = 4;
        String array[][] = new String[r][c];
        String temp = "";
        String input = "";
        for (int i = 0; i < nList.size(); i++) {
            temp = temp + nList.get(i).getCompanyName() + ",";
            temp = temp + nList.get(i).getModel() + ",";
            temp = temp + nList.get(i).getType() + ",";
            temp = temp + "Non Consumable";
            if (i < nList.size() - 1) {
                temp = temp + ",";
            }
        }
        for (int i = 0; i < cList.size(); i++) {
            input = input + cList.get(i).getCompanyName() + ",";
            input = input + cList.get(i).getTag() + ",";
            input = input + cList.get(i).getType() + ",";
            input = input + "Consumable";
            if (i < cList.size() - 1) {
                input = input + ",";
            }
        }
        String out = "";
        if (!temp.equals("") && (!input.equals(""))) {
            out = temp + "," + input;
        } else if (!temp.equals("")) {
            out = temp;
        } else if (!input.equals("")) {
            out = input;
        }
        String arr[] = out.split(",");
        int k = 0;

        for (int i = 0; i < r; i++) {
            for (int j = 0; j < c; j++) {
                if (k < arr.length) {
                    array[i][j] = arr[k];
                    k++;
                }
            }
        }
        return array;
    }

    void showDataN() {
        //homePanel.setVisible(true);
        itemName.setText("Non Consumable");
        categoryName.setText(ncObj.getType());
        homeCompanyName.setText(ncObj.getCompanyName());
        homeModel.setText(ncObj.getModel());
        homeYear.setText(ncObj.getYearOfManufacture());
        itemName.setEditable(false);
        categoryName.setEditable(false);
        homeCompanyName.setEditable(false);
        homeModel.setEditable(false);
        homeYear.setEditable(false);
    }

    void showDataC() {
        //homePanel.setVisible(true);
        itemName.setText("Consumable");
        categoryName.setText(cObj.getType());
        homeCompanyName.setText(cObj.getCompanyName());
        homeModel.setText(cObj.getTag());
        String a = "" + cObj.getTime();
        homeYear.setText(a);

        itemName.setEditable(false);
        categoryName.setEditable(false);
        homeCompanyName.setEditable(false);
        homeModel.setEditable(false);
        homeYear.setEditable(false);
    }

    String[][] ManagerTableDataN(List<NonConsumableAccessories> dataList) {
        int c = 3;
        int r = dataList.size();
        String[][] array = new String[r][c];
        String temp = "";
        for (int i = 0; i < dataList.size(); i++) {
            temp = temp + dataList.get(i).getCompanyName() + ",";
            temp = temp + dataList.get(i).getModel() + ",";
            temp = temp + dataList.get(i).getStatus();
            if (i < dataList.size() - 1) {
                temp = temp + ",";
            }
        }
        String arr[] = temp.split(",");
        int k = 0;
        for (int i = 0; i < r; i++) {
            for (int j = 0; j < c; j++) {
                if (k < arr.length) {
                    array[i][j] = arr[k];
                    k++;
                }
            }
        }
        return array;
    }

    String[][] ManagerTableDataC(List<ConsumableAccessories> dataList) {
        int c = 3;
        int r = dataList.size();
        String[][] array = new String[r][c];
        String temp = "";
        for (int i = 0; i < dataList.size(); i++) {
            temp = temp + dataList.get(i).getCompanyName() + ",";
            temp = temp + dataList.get(i).getTag() + ",";
            temp = temp + dataList.get(i).getStatus();
            if (i < dataList.size() - 1) {
                temp = temp + ",";
            }
        }
        String arr[] = temp.split(",");
        int k = 0;
        for (int i = 0; i < r; i++) {
            for (int j = 0; j < c; j++) {
                if (k < arr.length) {
                    array[i][j] = arr[k];
                    k++;
                }
            }
        }
        return array;
    }

    void createManagerTableN(List<NonConsumableAccessories> dataList) {
        String[][] rowData = ManagerTableDataN(dataList);
        String[] colHeader = {"Company Name", "Model", "Status"};
        DefaultTableModel model = (DefaultTableModel) managerTable.getModel();
        model.setDataVector(rowData, colHeader);
    }

    void createManagerTableC(List<ConsumableAccessories> dataList) {
        String[][] rowData = ManagerTableDataC(dataList);
        String[] colHeader = {"Company Name", "Tag No.", "Status"};
        DefaultTableModel model = (DefaultTableModel) managerTable.getModel();
        model.setDataVector(rowData, colHeader);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManagerFrame.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManagerFrame.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManagerFrame.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManagerFrame.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManagerFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton acceptButton;
    private javax.swing.JButton actionButton;
    private javax.swing.JButton adminButton1;
    private javax.swing.JButton adminButton2;
    private javax.swing.JButton adminButton3;
    private javax.swing.JButton adminButton4;
    private javax.swing.JButton adminButton5;
    private javax.swing.JTable allRequestTable;
    private javax.swing.JLabel categoryLabel;
    private javax.swing.JLabel categoryLabel1;
    private javax.swing.JTextField categoryName;
    private javax.swing.JTextField companyName;
    private javax.swing.JRadioButton consumableHome;
    private javax.swing.JRadioButton consumableRadio;
    private javax.swing.JButton deleteButton;
    private javax.swing.JButton editButton;
    private javax.swing.JTextField empEmail;
    private javax.swing.JTextField empEmail1;
    private javax.swing.JTextField empName;
    private javax.swing.JTextField empName1;
    private javax.swing.JTextField empPhone;
    private javax.swing.JTextField empPhone1;
    private javax.swing.JTable employeeRequest;
    private javax.swing.JTable employeeRequest1;
    private javax.swing.JButton generateButton;
    private javax.swing.JComboBox<String> homeComboBox;
    private javax.swing.JTextField homeCompanyName;
    private javax.swing.JRadioButton homeCompanyRadio;
    private javax.swing.JTextField homeModel;
    private javax.swing.JLabel homeModelLabel;
    private javax.swing.JRadioButton homeModelRadio;
    private javax.swing.JLabel homeNameLabel;
    private javax.swing.JPanel homePanel;
    private javax.swing.JTextField homeYear;
    private javax.swing.JLabel homeYearLabel;
    private javax.swing.JComboBox<String> itemComboBox;
    private javax.swing.JTextField itemName;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private com.toedter.calendar.JCalendar jCalendar1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable managerTable;
    private javax.swing.JTextField modelField;
    private javax.swing.JLabel modelLabel;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JRadioButton nonConsumableHome;
    private javax.swing.JRadioButton nonConsumableRadio;
    private javax.swing.JButton rejectButton;
    private javax.swing.JTextField reqIDField;
    private javax.swing.JTextField reqIDField1;
    private javax.swing.JPanel requestPanel;
    private javax.swing.JPanel requestPanel1;
    private javax.swing.JTable requestTable;
    private javax.swing.JButton searchButton;
    private javax.swing.JTextField searchField;
    private javax.swing.JButton viewButton;
    private javax.swing.JButton viewButton1;
    private javax.swing.JLabel yearLabel;
    // End of variables declaration//GEN-END:variables
}
